version: "3.3"

services:

  nginx:
    container_name: "nginx"
    image: nginx:1.16
    restart: always
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${domain}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/