version: '2'
services:
  nginx:
    image: nginx:alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - 'traefik.frontend.rule=Host:www.website.com'
      - "traefik.port=80"
    volumes:
      - ./website:/usr/share/nginx/html
  proxy:
    image: traefik
    command: --web -c /etc/traefik/traefik.toml --LOGLEVEL=debug
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /acme