version: '3.4'

services:
  traefik:
    image: traefik:v1.7.24
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik

  web:
    image: nginx:1.17-alpine
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.basic.frontend.rule=Host:your_domain"
      - "traefik.basic.protocol=http"
      - "traefik.enable=true"
    volumes:
      - ./logs/:/var/log/nginx/

networks:
  proxy:
    external: true