version: '3.0'
services:

  nginx:
    container_name: "nginx"
    image: nginx:1.16
    restart: always
    ports:
      - "80:80"
    links:
      - backend
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/